### ISSUE TITLE
Отпуска занесенные в старую систему, в новой не видны

### ISSUE THREAD

**Issue by kimspark** [UGTU/UGTUKadrProject#183]
Примеры: 
- Одинцова, 
- Орлова,
- Уланов С. И. (2015 г.)

**Comment by mail2sergk** [comment]
Оль, в таких случаях проси, пожалуйста, скриншоты отпусков в старой системе

UPD: я нашел причину, нужно обсудить

**Comment by mail2sergk** [comment]
Нашел скрипт для создания эвентов отпусков, но он оказался морально устаревшим. Нужна модификация:

INSERT INTO [dbo].[FactStaffPrikaz](idPrikaz,[idFactStaff],[DateBegin],[DateEnd])
SELECT DISTINCT idOtpuskPrikaz,[OK_Otpusk].[idFactStaff],[OK_Otpusk].[DateBegin],[OK_Otpusk].[DateEnd] 
FROM [dbo].[OK_Otpusk] 
LEFT JOIN [dbo].[FactStaffPrikaz] 
    ON [OK_Otpusk].[idFactStaff]=[FactStaffPrikaz].idFactStaff
        AND [OK_Otpusk].idOtpuskPrikaz=[FactStaffPrikaz].idPrikaz
        AND [OK_Otpusk].DateBegin=[FactStaffPrikaz].DateBegin
WHERE [FactStaffPrikaz].id IS nULL

**Comment by kimspark** [comment]
Фильтр, который отбирает отпуска в методе Read в class CRUDVacation, использует Event. В старой системе Event не заполняется, соответственно в нашей системе все отпуска, заполненные в старой системе убираются.

**Comment by kimspark** [comment]
--   создание Event  ----------------------------------------------------------------------------------------------------
INSERT INTO [dbo].Event(DateBegin, DateEnd, idContract, idEventKind, idEventType,idFactStaffHistory,idPrikaz)
  SELECT DISTINCT [OK_Otpusk].[DateBegin],[OK_Otpusk].[DateEnd], null, 15, 1, FSH.id, idOtpuskPrikaz
  FROM [dbo].[OK_Otpusk] inner join FactStaff on [OK_Otpusk].[idFactStaff]=FactStaff.id
  LEFT JOIN FactStaffHistory FSH on FactStaff.id = FSH.[idFactStaff] and 
    FSH.DateBegin = (select max(DateBegin) from FactStaffHistory TempFSH where  TempFSH.idFactStaff = FactStaff.id
                     and DateBegin<=[OK_Otpusk].DateBegin)
  WHERE [OK_Otpusk].idFactStaffPrikaz is null
  and FSH.id is not null 

--   ссылка на event в [OK_Otpusk]  --------------------------------------------------------------------------------
  update [OK_Otpusk] set idFactStaffPrikaz = (select top(1) Event.id 
                                              from Event,FactStaffHistory where Event.idPrikaz = [OK_Otpusk].idOtpuskPrikaz
                                              and Event.idFactStaffHistory = FactStaffHistory.id and FactStaffHistory.idFactStaff = [OK_Otpusk].idFactStaff
                                              and Event.DateBegin = [OK_Otpusk].DateBegin and Event.idEventKind = 15)
  where idFactStaffPrikaz is null
