### ISSUE TITLE
Добавление приказа: уже добавленный приказ не сразу отображается в списках при вводе других event

### ISSUE THREAD

**Issue by kimspark** [UGTU/UGTUKadrProject#199]
Например, для отпуска.
1. Ввели отпуск сотрудника, добавив при этом приказ.
2. Вводит отпуск для другого сотрудника, пытаясь выбрать тот же приказ.
3. В списке нужный приказ не появляется.

**Comment by mail2sergk** [comment]
"Ввели отпуск сотрудника, добавив при этом отпуск" - что?

**Comment by mail2sergk** [comment]
Не смог воспроизвести. Реквестирую подтверждение, что баг актуален.
