### ISSUE TITLE
При приеме сотрудника возникает проблема с контекстом.

### ISSUE THREAD

**Issue by kimspark** [UGTU/UGTUKadrProject#209]
Подозрение на то, что при приеме сотрудника используется сотрудник и его контекст из дерева. Скриншот прилагается:
![default](https://cloud.githubusercontent.com/assets/5836938/11033192/5c1b0c12-86f2-11e5-8590-5cde852db921.png)

**Comment by tanvok** [comment]
Эта же ошибка возникает на фрейме Сотрудник. У меня только одно предположение - используется текущий объект из DBGrid (FactStaff, PlanStaff) - возможно, он уже устарел.
Поэтому я ищу его по id. Возможно, это исправит ситуацию.
